### ISSUE TITLE
Change reference group in regression

### ISSUE THREAD

**Issue by star1327p** [bambinos/bambi#380] opened 2021-07-21 22:00 UTC
Bambi seems to use the default settings to determine the reference group in regression, and it is hard to change the reference group to a different value. For two groups, the coefficient in a linear model can simply be reverted to use the other group as the baseline. But things are more difficult to tweak when we have three or more groups to compare.

**Comment by tomicapretto** [comment] 2021-07-21 23:13
Hi @star1327p, thanks for opening this issue! 

This is still a weak point in Bambi, but it's not actually Bambi's fault. It's about formulae, the library Bambi uses to parse model formulas. 

[Here](https://bambinos.github.io/formulae/notebooks/getting_started.html#Categorical-predictors) you can see how to change the baseline level of categorical predictors as well as other things. 

I would like to improve how this is handled in the future. If you have any suggestions about what would be nice to have, just leave them here and I will take them into account :)

**Comment by star1327p** [comment] 2021-07-21 23:18
Thank you for the information!

**Comment by aflaxman** [comment] 2021-07-22 00:40
Hi All, thanks for your work on this library, it is a great addition to the Python Data Science arsenal.  I think it would be a lot cooler to say `design_matrices("y1 ~ C(z, reference=2)", data)` than the way it is accomplished now (IIUC) by `design_matrices("y1 ~ C(z, levels=lvls)", data)`.  Thanks again. --Abie

**Comment by tomicapretto** [comment] 2021-07-28 14:37
@aflaxman what is your aim when you say `C(z, reference=2)`? Do you want to have a 0-1 encoding where 1 represents the value `2` and `0` represents anything else, or do you want to have multiple levels, but making sure `2` is the baseline level?

If you want to have 0-1 encoding, you can use `C(z, ref=2)`. The latter isn't implemented yet, I'm working on it right now.

**Comment by tomicapretto** [comment] 2021-07-28 15:00
The solution I propose consists of having two helper functions `binary()` and `C()`. The first is invoked when you want to derive a 0-1 variable from another variable. The second is invoked when you want to convert one variable into categorical or manipulate their levels. Some examples

* `binary(variable, success)`

```python
# x is character with levels 'a', 'b', 'c'. 
# The level 'b' is converted to 1, everything else is 0.
design_matrices("y ~ binary(x, 'b')")

# x is numeric with values 1, 2, 3, 4, 5. 
# The value 5 is converted to 1, everything else is 0.
design_matrices("y ~ binary(x, 5)")
```
You could also use `binary(x)` and formulae will pick the value taken as success (encoded with a 1)

* `C(variable, reference, levels)`

```python
# x is character with levels 'a', 'b', 'c'.  
# The level 'c' is taken as baseline, all the rest mantain same order. 
# Resuling order 'c', 'a', 'b'
design_matrices("y ~ C(x, 'a')")

# x is numeric with values 1, 2, 3, 4, 5.  
# The value 5 is taken as baseline, all the rest mantain the same order.
# Resuling order 5, 1, 2, 3, 4
design_matrices("y ~ binary(x, 5)")

# x is character with values 'low', 'medium', 'high'.
# By default, the order is  'high', 'low', 'medium', but we want to keep  'low', 'medium', 'high'.
l = ['low', 'medium', 'high']
design_matrices("y ~ C(x, levels=l)")

# x is numeric with values 1, 2, 3.
# By default, the order is 1, 2, 3. But we want 3, 2, 1
l = [3, 2, 1]
design_matrices("y ~ C(x, levels=l)")
```

If you want to convert a variable to categorical without specifying order (which means you'll get default order) you can do `C(variable)`.

---

Last but not least, you could also pass a variable name instead of the value. For example

```python
ref = "This is a long variable name I don't want to type in my formula"
design_matrices("y ~ C(x, ref)")
design_matrices("y ~ binary(x, ref)")
```

**Comment by star1327p** [comment] 2021-07-29 00:39
@tomicapretto This is a great start! As a next step, I'd like to see examples of how the `design_matrices` are used in the bambi model.

**Comment by tomicapretto** [comment] 2021-07-29 01:16
> @tomicapretto This is a great start! As a next step, I'd like to see examples of how the `design_matrices` are used in the bambi model.

Cool :smile: ! 

You don't need to worry much about `design_matrices()` if you're not planning to use [formulae](https://github.com/bambinos/formulae) outside Bambi because Bambi already uses `design_matrices()` internally. For example, if you write something like 

```python
model = Model("response ~ x + binary(y) + C(z)", data)
```

Bambi passes both the formula and the data frame down to `design_matrices()` and then it works internally with the object it returns.

I'll try to post examples with Bambi and this new notation once we launch a new release (which should happen in August)

**Comment by aflaxman** [comment] 2021-07-29 05:17
> @aflaxman what is your aim when you say `C(z, reference=2)`? Do you want to have a 0-1 encoding where 1 represents the value `2` and `0` represents anything else, or do you want to have multiple levels, but making sure `2` is the baseline level?
> 
> If you want to have 0-1 encoding, you can use `C(z, ref=2)`. The latter isn't implemented yet, I'm working on it right now.

multiple levels, with 2 as reference --- as could now be achieved with `C(z, levels=[2,1,3,4])` IIUC.

**Comment by tomicapretto** [comment] 2021-08-04 20:58
The solution proposed above has been merged into the main branch.

If you do `C(z, 2)` or `C(z, reference=2)` it means you keep all the levels but 2 is now the reference/baseline.
This function is documented [here](https://github.com/bambinos/formulae/blob/f89a040e32746e3a76a203ddcea072403da33f5f/formulae/transforms.py#L56-L80): 

Feel free to reopen if you find a bug or want to clarify something :smile:

**Closed by tomicapretto** 2021-08-04 20:58 UTC

**Comment by jankaWIS** [comment] 2024-09-11 11:55
Hi, 

I was also looking into how to set a certain value as a baseline in Bambi. I have the following questions/comments.

1. If you use the `C()` notation, it also changes the variable name to that.

So, for instance:
```python
bambi_test_data = pd.DataFrame({
    'response': np.random.randint(0,10,12),
    'x': np.arange(12),
    'y': ['a', 'b']*6,
    'z': ['aa', 'bb', 'cc']*4,
})

model = bmb.Model(
    formula="response ~ x * C(z)",  
    data=bambi_test_data,
)
model
```

would give you `C(z)` as a variable name and not `z` which would be what I would expect. It can be even messier if you add the interaction term as that will be `x:C(z)` and not just `x:z`, which, with the more complicated model or naming, stops being neat.

2. Specifying the reference level is, at least to me, not intuitive. Say you want to set level `aa` as the reference, then following this reply (https://github.com/bambinos/bambi/issues/380#issuecomment-888382229):
>
```
# x is character with levels 'a', 'b', 'c'.  
# The level 'c' is taken as baseline, all the rest mantain same order. 
# Resuling order 'c', 'a', 'b'
design_matrices("y ~ C(x, 'a')")
```

I'd write this code:

```python
model = bmb.Model(
    formula="response ~ x * C(z, 'aa')",  
    data=bambi_test_data,
)
```

which gives you this error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[39], line 8
      1 bambi_test_data = pd.DataFrame({
      2     'response': np.random.randint(0,10,12),
      3     'x': np.arange(12),
      4     'y': ['a', 'b']*6,
      5     'z': ['aa', 'bb', 'cc']*4,
      6 })
----> 8 model = bmb.Model(
      9     formula="response ~ x * C(z, 'aa')",  
     10     data=bambi_test_data,
     11 )
     12 model

File ~/.conda/envs/pymc_env_5/lib/python3.12/site-packages/bambi/models.py:169, in Model.__init__(self, formula, data, family, priors, link, categorical, potentials, dropna, auto_scale, noncentered, center_predictors, extra_namespace)
    167     design = remove_common_intercept(design)
    168 else:
--> 169     design = fm.design_matrices(
    170         self.formula.main, self.data, na_action, 1, additional_namespace
    171     )
    173 if design.response is None:
    174     raise ValueError(
    175         "No outcome variable is set! "
    176         "Please specify an outcome variable using the formula interface."
    177     )

File ~/.conda/envs/pymc_env_5/lib/python3.12/site-packages/formulae/matrices.py:556, in design_matrices(formula, data, na_action, env, extra_namespace)
    553     else:
    554         raise ValueError(f"'data' contains {incomplete_rows_n} incomplete rows.")
--> 556 design = DesignMatrices(description, data, env)
    557 return design

File ~/.conda/envs/pymc_env_5/lib/python3.12/site-packages/formulae/matrices.py:54, in DesignMatrices.__init__(self, model, data, env)
     51 self.model = model
     53 # Evaluate terms in the model
---> 54 self.model.eval(data, env)
     56 if self.model.response:
     57     self.response = ResponseMatrix(self.model.response)

File ~/.conda/envs/pymc_env_5/lib/python3.12/site-packages/formulae/terms/terms.py:1254, in Model.eval(self, data, env)
   1244 """Evaluates terms in the model.
   1245 
   1246 Parameters
   (...)
   1251     The environment where values and functions are taken from.
   1252 """
   1253 # Set types on all terms
-> 1254 self.set_types(data, env)
   1256 # Evaluate common terms
   1257 encodings = self._get_encoding_bools()

File ~/.conda/envs/pymc_env_5/lib/python3.12/site-packages/formulae/terms/terms.py:1161, in Model.set_types(self, data, env)
   1149 """Set the type of the terms in the model.
   1150 
   1151 Calls ``.set_type()`` method on term in the model.
   (...)
   1158     The environment where values and functions are taken from.
   1159 """
   1160 for term in self.terms:
-> 1161     term.set_type(data, env)

File ~/.conda/envs/pymc_env_5/lib/python3.12/site-packages/formulae/terms/terms.py:433, in Term.set_type(self, data, env)
    431     component.set_type(data)
    432 elif isinstance(component, Call):
--> 433     component.set_type(data, env)
    434 else:
    435     raise ValueError(
    436         "Can't set type on Term because at least one of the components "
    437         f"is of the unexpected type {type(component)}."
    438     )

File ~/.conda/envs/pymc_env_5/lib/python3.12/site-packages/formulae/terms/call.py:109, in Call.set_type(self, data_mask, env)
    107 transforms_env = Environment([{**TRANSFORMS, **ENCODINGS}])
    108 self.env = transforms_env.with_outer_namespace(env.namespace)
--> 109 x = self.call.eval(data_mask, self.env)
    111 if is_numeric_dtype(x):
    112     self.kind = "numeric"

File ~/.conda/envs/pymc_env_5/lib/python3.12/site-packages/formulae/terms/call_resolver.py:267, in LazyCall.eval(self, data_mask, env)
    264 args = [arg.eval(data_mask, env) for arg in self.args]
    265 kwargs = {name: arg.eval(data_mask, env) for name, arg in self.kwargs.items()}
--> 267 return callee(*args, **kwargs)

File ~/.conda/envs/pymc_env_5/lib/python3.12/site-packages/formulae/transforms.py:89, in C(data, contrast, levels)
     87         levels = data.levels
     88     data = data.data
---> 89 return CategoricalBox(data, contrast, levels)

File ~/.conda/envs/pymc_env_5/lib/python3.12/site-packages/formulae/categorical.py:83, in CategoricalBox.__init__(self, data, contrast, levels)
     81     levels = data.dtype.categories.tolist()
     82 self.data = data
---> 83 self.contrast = contrast
     84 self.levels = levels

File ~/.conda/envs/pymc_env_5/lib/python3.12/site-packages/formulae/categorical.py:109, in CategoricalBox.contrast(self, value)
    106     value = value()
    108 if not (isinstance(value, Encoding) or value is None):  # pragma: no cover
--> 109     raise ValueError("The contrast argument in must be an instance of Encoding")
    110 self._contrast = value

ValueError: The contrast argument in must be an instance of Encoding
```

I don't understand why that happens, to be honest.

3. Because of 2., I decided to do the workaround and specify the levels manually:

```python
l = ['aa', 'bb', 'cc']
model = bmb.Model(
    formula="response ~ x * C(z, levels=l)",  
    data=bambi_test_data,
)
model
```

This, however, leads to even uglier variable names, as the entire text gets passed to the var name (e.g. `x:C(z, levels=l)`), see point 1 and below:
```
       Formula: response ~ x * C(z, levels=l)
        Family: gaussian
          Link: mu = identity
  Observations: 12
        Priors: 
    target = mu
        Common-level effects
            Intercept ~ Normal(mu: 3.5, sigma: 15.197)
            x ~ Normal(mu: 0.0, sigma: 1.9274)
            C(z, levels=l) ~ Normal(mu: [0. 0.], sigma: [14.1145 14.1145])
            x:C(z, levels=l) ~ Normal(mu: [0. 0.], sigma: [2.0561 1.8356])
        
        Auxiliary parameters
            sigma ~ HalfStudentT(nu: 4.0, sigma: 2.6615)
```

4. Is there a reason why not to do it like this? This could be done under the hood, and Bambi could have a parameter that would go to `categories` and determine the order. It could be then even possible to pass a single item and create a list where this item is first and the rest is kept in the order of the dataset.

```python
bambi_test_data = pd.DataFrame({
    'response': np.random.randint(0,10,12),
    'x': np.arange(12),
    'y': ['a', 'b']*6,
    'z': ['aa', 'bb', 'cc']*4,
})

bambi_test_data['z_cat'] = pd.Categorical(bambi_test_data['z'], categories=['aa', 'bb', 'cc'], ordered=True)

model = bmb.Model(
    formula="response ~ x * z",  
    data=bambi_test_data,
)
model
```


Thanks.

**Comment by tomicapretto** [comment] 2024-09-12 13:37
Hi @jankaWIS! Thanks for sharing all the questions, I'll try to answer them

1. This is because we're using a function call in the model formula, then we need to respect that name. It's as if you did `y ~ center(x)`. Then the name won't be `x`, it will be `center(x)`. Same if you do `y ~ log(x)` or `log(y) ~ x`.  
One thing you can do in this case is using an alias to get a clearer name. See `Model.set_alias()` here https://bambinos.github.io/bambi/notebooks/hsgp_1d.html#hsgp-by-levels-of-a-categorical-covariate
2. Sorry, that comment is outdated. Since then, we allow for more flexible contrast matrices. `C()` is the general function that allows to pass a contrast as the second argument. [This](https://github.com/bambinos/formulae/blob/151db43f7a0717b39aa9aa93c69a850ea1202424/formulae/transforms.py#L82-L105) is where these functions are defined, in formulae. And [here](https://github.com/bambinos/formulae/blob/151db43f7a0717b39aa9aa93c69a850ea1202424/tests/test_design_matrices.py#L701-L733) you can see some examples in the tests. To achieve what you want you can do `T(z, 'aa')`. `T()` stands for treatment encoding (which is the one where we set a reference level to zero) and there's also `S()` which stands for zero-sum encoding (which is the one where the sum of coefficients is equal to zero).
3. While that could work, I recommend following what I said in 2.
4. Are you saying we could modify our [`categorical`](https://github.com/bambinos/bambi/blob/516d7bd4fcfd2aea1b355f6873f45271ad48cf71/bambi/models.py#L66-L71) parameter so it can receive, for example, a dictionary where keys are names of variables and values are lists with the custom order? That _could_ work, but I think users should do it on their own, outside the model definition. They can control better potential errors. Finally, ine example you shared, you should write `response ~ x * z_cat` and it would work.

**Comment by jankaWIS** [comment] 2024-09-13 08:34
Hi @tomicapretto and thank you for the quick and super useful response. My comments are below.

1. I didn't know about this function to set aliases, it's super useful, thanks!
2. I see. I'm sorry, I didn't read the error message before correctly, now I see that it's not an instance of `Encoding`, I somehow read it as that it needs to be present in the data... Could you please maybe elaborate more (or send me to the relevant docs section) on how exactly the formulae works? I see that the `T` and `S` are shorthands for `Treatment` and `Sum` within the `C` function, but the `C` should also allow you to pass the levels - as you say and as is written in the definition of the function. So why doesn't `C(z, levels='aa')` work? And how are the variables passed? For instance, I'm still puzzled by `formula="response ~ x * C(z, levels=l)"` and why it works as it's not an f-string.
3. Ok.
4. First of all, sorry, my bad, there is a typo in my code and it should have been `z_cat` instead of `z`. Secondly, I didn't think about it this way but yes, that could work to be able to pass a dictionary with order for the categories. I thought of adding a separate parameter with the order which would be a dictionary for the different categories and then the ordering would be done within bambi's `Model`. But your argument of leaving it to the user to do it outside and avoid potential errors is a good and sufficient one :).

**Comment by jankaWIS** [comment] 2025-02-05 12:11
Hi, me again :),

I have come across a behaviour that is, on the one hand, obvious, but on the other, I'm not sure how to fix it. Say you are running several models or the same model on several datasets. For that purpose, you may want to write the following function:

```python
def fit_model(formula, data, num_cpu=1, **kwargs):
    # create the model
    model = bmb.Model(
        formula=formula,
        data=data,
        dropna=True,
        **kwargs
    )
    # fit the model
    print(f'Using {num_cpu} core(s).')
    results = model.fit(cores=num_cpu)

    return model, results
```

That all is great but now you want to have this function in a separate file and load it as a module. In that case, if you have this function outside of your environment and want to run:
```python
base_lvl= ['aa', 'bb', 'cc']
formula="response ~ x * C(z, levels=base_lvl)", 
fit_model(formula, data)
```

you will get a `KeyError: 'base_lvl'` that is raised by the design matrices.
The issue is that the `base_lvl` is not defined within the scope of the function and is defined only outside. But the [`model`](https://bambinos.github.io/bambi/api/Model.html#bambi.Model) doesn't have a way to pass anything down, so how do you solve such an issue?

The workaround I have is to define a variable within the function and then pass that variable as an argument (as below). That works but there must be a better way to do that. What do you think?

```python
def fit_model(formula, data, base_lvl=None, num_cpu=1, **kwargs):
```


<details>
<summary>KeyError</summary>

```
File ~/.conda/envs/pymc_env_5/lib/python3.12/site-packages/bambi/models.py:169, in Model.__init__(self, formula, data, family, priors, link, categorical, potentials, dropna, auto_scale, noncentered, center_predictors, extra_namespace)
    167     design = remove_common_intercept(design)
    168 else:
--> 169     design = fm.design_matrices(
    170         self.formula.main, self.data, na_action, 1, additional_namespace
    171     )
    173 if design.response is None:
    174     raise ValueError(
    175         "No outcome variable is set! "
    176         "Please specify an outcome variable using the formula interface."
    177     )

File ~/.conda/envs/pymc_env_5/lib/python3.12/site-packages/formulae/matrices.py:556, in design_matrices(formula, data, na_action, env, extra_namespace)
    553     else:
    554         raise ValueError(f"'data' contains {incomplete_rows_n} incomplete rows.")
--> 556 design = DesignMatrices(description, data, env)
    557 return design
```

</details>

**Comment by tomicapretto** [comment] 2025-02-05 14:55
@jankaWIS it works that way because we inspect only the environment where `bmb.Model` is intialized, not upper levels. I think the following could work

```python
def f(...):
    ....
    model = bmb.Model(..., extra_namespace=dict(globals(), **locals()))
    ...
```

which makes usage of the `extra_namespace` argument documented in https://bambinos.github.io/bambi/api/Model.html#bambi.Model

**Comment by jankaWIS** [comment] 2025-02-05 15:02
It does look scary to pass all the local and global variables :D. I think I'll stay with my workaround but thanks a lot for your quick answer and for the suggestion.
