### ISSUE TITLE
Error when compute pps in Cumulative Model, the version of bambi is 0.14.0

### ISSUE THREAD

**Issue by wenboyu0803** [bambinos/bambi#858] opened 2024-11-21 23:43 UTC
Hi, i encounter an error when run bayes model

idata_pps = model.predict(idata = idata, kind="response", inplace=False)

AttributeError: module 'xarray' has no attribute 'Coordinates'

Thanks

Wenbo

**Comment by GStechschulte** [comment] 2024-11-25 15:26
Hey @wenboyu0803 apologies for the delayed response. At the moment, I can't reproduce your error as I am (for some weird reason) getting multiprocessing errors when fitting a cumulative model. Once I get this resolved, I will circle back here.

**Comment by tomicapretto** [comment] 2024-11-26 18:56
Hi @wenboyu0803 do you have a minimum example I can run? Also, do you know which versions of arviz, bambi, and xarray you're running?

**Comment by tomicapretto** [comment] 2024-11-26 18:59
`xarray.Coordinates` were introduced in v2023.08.0 of `xarray` (see https://github.com/pydata/xarray/releases/tag/v2023.08.0). I think you are using an old version.

**Comment by wenboyu0803** [comment] 2024-11-28 06:45
hi @tomicapretto 
i will check the version of xarray these days.
if it still does not work, i will show you my data.
Thanks.

**Comment by wenboyu0803** [comment] 2024-12-27 07:44
hi @tomicapretto 
i still could not solve the bayes model with bambi, would you help me check my model ?
here is my model and all data.

the dependent variable is "RV", independent variable is "GAP". i want to used sdif contrast, that is, i want to compare the difference of RV between g200 and g350, the difference of RV between g350 and g500, the difference of RV between g500 and g650, the difference of RV between g650 and g800, the difference of RV between g800 and g950.

```
df_raw["GAP"] = pd.Categorical(df_raw["GAP"], ordered=False)
df_raw["RV"] = pd.Categorical(df_raw["RV"], ordered=True)
df_raw["sti.frame"] = pd.Categorical(df_raw["sti.frame"], ordered=False)
df_raw["Subject"] = pd.Categorical(df_raw["Subject"], ordered=False)

model_hd = bmb.Model(
    "RV ~ GAP + (1|Subject) + (1|sti.frame), contrast = Diff()", 
    priors = priors,
    data = df_raw,
    family="cumulative")
model_hd

```
[data.bayes.xlsx](https://github.com/user-attachments/files/18258435/data.bayes.xlsx)


Great thanks

**Comment by tomicapretto** [comment] 2024-12-28 02:25
I can't reproduce the problem. It actually works pretty well! See my code:

```python
import arviz as az
import bambi as bmb
import pandas as pd

df = pd.read_excel("data/data.bayes.xlsx")
df.info()
```

```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1104 entries, 0 to 1103
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Subject    1104 non-null   object
 1   RV         1104 non-null   int64 
 2   sti.frame  1104 non-null   int64 
 3   GAP        1104 non-null   object
dtypes: int64(2), object(2)
memory usage: 34.6+ KB
```

```python
df["GAP"] = pd.Categorical(df["GAP"], ordered=False)
df["RV"] = pd.Categorical(df["RV"], ordered=True)

df["sti.frame"] = pd.Categorical(df["sti.frame"], ordered=False)
df["Subject"] = pd.Categorical(df["Subject"], ordered=False)

priors = {
    "GAP": bmb.Prior("Normal", mu=0, sigma=0.5),
    "1|Subject": bmb.Prior("Normal", mu=0, sigma=bmb.Prior("HalfNormal", sigma=1)),
    "1|sti.frame": bmb.Prior("Normal", mu=0, sigma=bmb.Prior("HalfNormal", sigma=1))
}

model_hd = bmb.Model(
    "RV ~ 0 + GAP + (1|Subject) + (1|sti.frame)",
    data=df,
    family="cumulative",
    priors=priors
)
model_hd
```

```
       Formula: RV ~ 0 + GAP + (1|Subject) + (1|sti.frame)
        Family: cumulative
          Link: p = logit
  Observations: 1104
        Priors: 
    target = p
        Common-level effects
            GAP ~ Normal(mu: 0.0, sigma: 0.5)
        
        Group-level effects
            1|Subject ~ Normal(mu: 0.0, sigma: HalfNormal(sigma: 1.0))
            1|sti.frame ~ Normal(mu: 0.0, sigma: HalfNormal(sigma: 1.0))
        
        Auxiliary parameters
            threshold ~ Normal(mu: [-2.  -1.2 -0.4  0.4  1.2  2. ], sigma: 1.0, transform: ordered)
```

```python
idata = model_hd.fit()
```

![image](https://github.com/user-attachments/assets/ed56ed5b-79d6-4ed1-8029-9589f5e344a9)


```python
az.plot_trace(idata, backend_kwargs={"layout": "constrained"});
```

![image](https://github.com/user-attachments/assets/816812ab-1b74-4b23-acd7-32f0cb67e9d2)


```python
%load_ext watermark
%watermark -n -u -v -iv -w
```

```
Last updated: Fri Dec 27 2024

Python implementation: CPython
Python version       : 3.11.9
IPython version      : 8.27.0

arviz : 0.19.0
pandas: 2.2.3
bambi : 0.15.0

Watermark: 2.5.0
```

---

**Note that** I have removed the intercept (as it's omitted) and I've also used some custom priors (it seems you were doing that too, but just didn't share them).

**Comment by wenboyu0803** [comment] 2024-12-29 12:42
hi @tomicapretto
thanks for your share. 
i reproduce your code perfectly and the error might lie in the version of packages.
Another quesition, i want to ask. if i want to use "sdif contrast", how can i achieve it in bambi?
When i analyzed the same data with brms in R, i just wrote "contrasts(hd$GAP) <- contr.sdif", but i could not reproduce the similar analysis in bambi. 

Thanks

**Comment by tomicapretto** [comment] 2024-12-30 12:43
@wenboyu0803 It's not possible to do that with Bambi now. The problem does not lie in Bambi itself, but in the formula library we use under the hood. We don't have a great documentation about the different contrasts, but this is a comment I write some time ago https://github.com/bambinos/bambi/issues/380#issuecomment-2366933535.

To make this available in Bambi, we would need to add the sdif contrast to formulae, then it would be trivial to use it in Bambi.

**Comment by tomicapretto** [comment] 2024-12-30 12:43
@wenboyu0803 I'm going to close the issue because the original concern is already answered. Feel free to open another issue if you have other questions!

**Closed by tomicapretto** 2024-12-30 12:43 UTC
Labels: bug
