### ISSUE TITLE
Setting Prior on only one group term

### ISSUE THREAD

**Issue by tjburch** [bambinos/bambi#778] opened 2024-02-10 17:34 UTC
I'm wanting to set a prior on a single level of a group, but not the others. Is this possible to do? 

Here's a MWE:

```
np.random.seed(1)
group = np.repeat(['A', 'B', 'C'], 50)
x = np.concatenate([np.linspace(0, 5, 50), np.linspace(0, 5, 50), np.linspace(0, 5, 50)])  
intercept_a = 1
intercept_b = 4
intercept_c = 7 
slope = 2
noise = np.random.normal(0, 1, 150) 

y = np.where(group == 'A', intercept_a + slope * x + noise, 
             np.where(group == 'B', intercept_b + slope * x + noise, intercept_c + slope * x + noise))

data = pd.DataFrame({'group': group, 'x': x, 'y': y})

# Plot the data
plt.figure(figsize=(10, 6))
plt.scatter(data[data['group'] == 'A']['x'], data[data['group'] == 'A']['y'], color='blue', label='Group A')
plt.scatter(data[data['group'] == 'B']['x'], data[data['group'] == 'B']['y'], color='red', label='Group B')
plt.scatter(data[data['group'] == 'C']['x'], data[data['group'] == 'C']['y'], color='green', label='Group C') 
plt.legend()
plt.xlabel('x')
plt.ylabel('y')
plt.show()
```

![image](https://github.com/bambinos/bambi/assets/16945590/9389345d-6710-43a2-a107-198c343d46d0)

First I want to fit a model:

```
model = bmb.Model('y ~ x + group', data, priors=priors)
model.build()
model.plot_priors()
```

This gives intercepts for groups B and C

```
print(az.summary(fit).iloc[:,0:4])
            mean     sd  hdi_3%  hdi_97%
Intercept  0.858  0.179   0.535    1.209
x          2.045  0.048   1.950    2.133
group[B]   3.178  0.180   2.857    3.524
group[C]   6.111  0.184   5.784    6.469
y_sigma    0.894  0.052   0.795    0.991
```

Now, say I know something specific about group C that makes me want to put a strong prior on it, I would expect this should work:

```

priors = {
    "group[C]": bmb.Prior('Normal', mu=7, sigma=1)
}
model = bmb.Model('y ~ x + group', data, priors=priors)
model.build()
model.plot_priors()
```

But when I plot priors it's not represented:

![image](https://github.com/bambinos/bambi/assets/16945590/eaf59e4f-48f3-4acc-8993-49a9b51e55a2)

I can, however, set a prior on `group` as a whole, which is used. 

```

priors = {
    "group": bmb.Prior('Normal', mu=4, sigma=1)
}
model = bmb.Model('y ~ x + group', data, priors=priors)
model.build()
model.plot_priors()
```

![image](https://github.com/bambinos/bambi/assets/16945590/e75297c8-77f5-4b54-bc8a-1f3becefb144)

**Comment by GStechschulte** [comment] 2024-02-13 17:36
@tjburch I also get the same results. One way of resolving the problem is to change the reference level using the `C()` wrapper to make the level C the reference level to which A and B are compared to. Then, set your prior on the intercept.

```python3
priors = {
    "Intercept": bmb.Prior("Normal", mu=4, sigma=1)
}

# C is reference with A and B being compared to C
lvls = ["C", "A", "B"]
model = bmb.Model("y ~ x + C(group, levels=lvls)", data, categorical="group", priors=priors)
model.build()
model.plot_priors(figsize=(12, 5))
plt.tight_layout();
```
![image](https://github.com/bambinos/bambi/assets/63432018/b99a9595-3f06-43ee-846c-d24a81531b0f)

However, this doesn't scale to if you want to set a prior on multiple levels of the categorical variable. @tomicapretto do you have any thoughts?

**Comment by tjburch** [comment] 2024-02-13 17:40
Yeah. The reference class solution I'm doing in the interim, and is more than fine for my case. I could see a case for having this ability for many levels, if for example there's well-defined constraints for level A and B but less is known about C and D, and you want a unified model containing all 4.

**Comment by GStechschulte** [comment] 2024-02-13 17:43
> Yeah. The reference class solution I'm doing in the interim, and is more than fine for my case. I could see a case for having this ability for many levels, if for example there's well-defined constraints for level A and B but less is known about C and D, and you want a unified model containing all 4.

Yup, definitely agree! Thanks! 👍🏼

**Comment by zwelitunyiswa** [comment] 2024-02-18 17:58
I like that. Super useful!

**Comment by tjburch** [comment] 2024-02-18 23:50
Thanks @tomicapretto!

**Closed** 2024-02-18 23:50 UTC
