### ISSUE TITLE
bambi.interpret.prediction fails for polynomial regression models

### ISSUE THREAD

**Issue by tjburch** [bambinos/bambi#772] opened 2024-01-17 02:18 UTC
When doing polynomial regression, the `interpret.prediction` method can't seem to handle polynomial terms within the formula. A MWE:

```
np.random.seed(0)
x1 = np.random.normal(size=100)
x2 = np.random.normal(size=100)
y = 2 + 3*x1 + 1.5*x1**2 + 2*x2 + np.random.normal(scale=1, size=100)
data = pd.DataFrame({'x1': x1, "x2": x2, 'y': y})
model = bmb.Model('y ~ poly(x1, 2) + x2', data)
results = model.fit()
bmb.interpret.predictions(model, results, "x2")
```

Gives the following error: `AttributeError: 'LazyOperator' object has no attribute 'name'`

The same thing also happens if you do `y ~ I{x**2} + x` as the formula.

**Comment by tomicapretto** [comment] 2024-01-22 12:23
@tjburch thanks for reporting the issue. Just want to mention the error I get is `AttributeError: 'LazyValue' object has no attribute 'name'`.

This is related to formulae. For every argument passed in the function call, formulae creates a representation of that object (i.e. an instance of some `Lazy*` class). When the argument passed is a variable name (i.e. it's an instance of `LazyVariable`) we can access the name of that variable with the `name` attribute. Other objects, such as values, don't have an `name` attribute.

The problem is that Bambi is looking for the name of the argument value `2` in `poly(x1, 2)`. 

@GStechschulte I see you self-assigned this to you. The solution that I found is using the following

```python
covariates.append([arg.name for arg in component.call.args if isinstance(arg, LazyVariable)])
```

in here

https://github.com/bambinos/bambi/blob/1a3cf8ad49add076c7daea6c29e7b09a267f2cb7/bambi/interpret/utils.py#L239-L240

where `LazyVariable` comes from `from formulae.terms.call_resolver import LazyVariable`.

**Comment by GStechschulte** [comment] 2024-01-22 13:07
@tomicapretto thanks for the comment. I also get the same error as you. I was working on this over the weekend and came to roughly the same solution as you. 

Once I add tests, I will open a PR 👍🏼

**Comment by GStechschulte** [comment] 2024-01-22 13:20
Sounds great @tjburch looking forward!

**Closed** 2024-01-23 22:31 UTC
Labels: bug
