### ISSUE TITLE
predict with inplace=False modifies idata 

### ISSUE THREAD

**Issue by luxspes** [bambinos/bambi#494] opened 2022-04-26 00:36 UTC
The `inplace` modifier on `predict(idata, kind='mean', data=None, draws=None, inplace=True, include_group_specific=True)` does not work, the idata gets modified: an independent_variable_mean_obs dimension gets added, and after that, predict cannot be used to predict again, as it then wants that independent_variable_mean_obs to part of the `data` input dataset.

arviz_version :
    0.11.4
inference_library :
    pymc3
inference_library_version :
    3.11.4
modeling_interface :
    bambi
modeling_interface_version :
    0.7.1

**Comment by tomicapretto** [comment] 2022-04-26 01:41
@luxspes thanks for opening this issue! Could you share a reproducible example so I can detect where the problem is happening? 

Maybe you're passing the modified `idata` to a new `.predict()` call?

**Comment by luxspes** [comment] 2022-04-26 12:12
Try for example this code: 

https://bambinos.github.io/bambi/main/notebooks/ESCS_multiple_regression.html 

right after you do this:

```
model = bmb.Model("drugs ~ o + c + e + a + n", data)
fitted = model.fit(tune=2000, draws=2000, init="adapt_diag", random_seed=SEED)
```

do this:

`posterior_predictive = model.predict(fitted, draws=500, inplace=False)`

and then do it again (it should work, as, given we are telling it `inplace=False` fitted should not have changed, right?):

`posterior_predictive = model.predict(fitted, draws=500, inplace=False)`

but you get an exception:

```
ValueError: Dataset does not contain the dimensions: {'drugs_mean_obs'}
```

apparently the first call to predict added drugs_mean_obs to fitted, and after that, it is cannot be used anymore.

**Comment by tomicapretto** [comment] 2022-04-26 12:28
Ohh, that is similar to #485. It's a bug in 0.7.1 release. Could you install from the dev version and try again?

**Comment by tomicapretto** [comment] 2022-05-09 22:10
Closing because of non-response.

**Closed by tomicapretto** 2022-05-09 22:10 UTC
