### ISSUE TITLE
plotting with bernoulli response raises KeyError

### ISSUE THREAD

**Issue by wcbeard** [bambinos/bambi#116] opened 2017-11-30 04:20 UTC
When trying to plot a result (modelling `y` as bernoulli) I get `KeyError: 0`

This occurs twice in the results.py file, around [here](https://github.com/bambinos/bambi/blob/e1abd5dd4d2aecd2e8474d4ee6d3191a0193a53e/bambi/results.py#L263) and [here](https://github.com/bambinos/bambi/blob/e1abd5dd4d2aecd2e8474d4ee6d3191a0193a53e/bambi/results.py#L353)

with the code

```
warnings.warn('Modeling the probability that {}==\'{}\''.format(
                self.model.y.name,
str(self.model.data[self.model.y.name][event])))
```

Elsewhere in [models.py](https://github.com/bambinos/bambi/blob/e1abd5dd4d2aecd2e8474d4ee6d3191a0193a53e/bambi/models.py#L218), similar code correctly works for me during `build()`, using

```
warnings.warn('Modeling the probability that {}==\'{}\''.format(
self.y.name, str(self.data[self.y.name].iloc[event])))
```

**Comment by jake-westfall** [comment] 2017-11-30 05:23
Can you post a minimal reproducible example? Or at least post the syntax you used and tell us something about your dataset, especially the variables that you specifically reference in the model formula?

**Comment by wcbeard** [comment] 2017-12-01 15:35
sure:

```
from bambi import Model
import numpy.random as nr

def inverse_log_odds(z):
    return 1.0 / (1.0 + np.exp(-z))

nr.seed(0)
Xy = DataFrame(nr.randint(0, 2, (100, 2)), columns=['x1', 'x2'])
logits = Xy.x1 * 2 + Xy.x2 * -1
Xy['y'] = nr.binomial(1, p=inverse_log_odds(logits))
model = Model(data=Xy)
model.add('y ~ 1', family='bernoulli')
model.add('x1')
model.add('x2')

%time res = model.fit()

res.plot() # => keyerror
```

**Comment by djmannion** [comment] 2018-03-24 02:31
I have come across this KeyError too. It was happening for me because my data frame indices did not increment by 1 on each row (skipped even numbers), so the ```event``` identified in the code was not addressable.

**Comment by aloctavodia** [comment] 2019-03-31 13:15
Closing as I am not able to reproduce this

**Closed by aloctavodia** 2019-03-31 13:15 UTC
