### ISSUE TITLE
Calling `add_formula` after `add_y` erases the y variable 

### ISSUE THREAD

**Issue by jake-westfall** [bambinos/bambi#43] opened 2016-09-11 05:49 UTC
For example, this works fine:

    model.add_formula('condition + gender', random='condition|subject')
    model.add_y('rt')

But reversing the order of the terms does not work:

    model.add_y('rt')
    model.add_formula('condition + gender', random='condition|subject')

After calling `add_formula`, the `y` attribute of the model disappears, so attempting to build the model fails with an error.

**Comment by tyarkoni** [comment] 2016-09-11 18:17
This is by design, sort of. `add_formula` has an `append` argument that's `False` by default, in which case it will reset the model before adding the new terms. The reason for this is that `add_formula` will typically be called from `fit`. But I agree that for consistency, we should probably set `append=True` by default, and then set it to `False` when calling it from `fit()`.

**Comment by tyarkoni** [comment] 2016-09-18 13:32
Closed in d531da7d151.

**Closed by tyarkoni** 2016-09-18 13:32 UTC
Labels: bug
