### ISSUE TITLE
Revisit Automatic Priors in Bambi and possibly improve automatic priors

### ISSUE THREAD

**Issue by canyon289** [bambinos/bambi#230] opened 2020-07-30 18:26 UTC
Adding an issue for revisiting the Automatic Priors in Bambi and double checking they still make sense.

Issue ticket spurred from this comment
![image](https://user-images.githubusercontent.com/7213793/88959736-5186d500-d257-11ea-858d-0c3affd432c9.png)

**Comment by jake-westfall** [comment] 2020-08-08 16:40
Feel free to reach out if you have questions about the current implementation of default priors. I'm not too interested at this time in spending time contributing new code myself, but happy to at least try and remember what we were thinking when we did it :)

Looking back on this work on default priors 3-4 years later, here's my top of head thoughts:
- For the fixed intercept and slope parameters, the current approach still seems pretty good. The underlying theory ([from the arxiv paper](https://arxiv.org/abs/1702.01201)) still seems reasonable to me and, practically speaking, the approach seems to yield pretty sensible "weakly informative" defaults for these parameters.
- For the random effect variances, from a purely practical perspective the defaults on these seem to turn out sensible enough in all the examples I've seen, but the underlying justification is a bit lacking. I mean, there's not really any explicit theoretical argument in my paper at all, just a vague intuitive argument that it seems like a reasonable way to do it. So this can probably be improved, but I don't immediately know the best way. At this point you guys probably know more than me about what good alternative options are.
- For the residual variance in Normal models, in retrospect I'm not real satisfied with how we handled these. My main concern is that I no longer buy the argument in my paper that we can deduce the upper bound on this parameter (for a uniform prior) from the observed data. As for the flat shape itself, I think this choice was basically equivocation on my part due to my uncertainty about what an appropriate shape for this prior should be. On one hand, since it's a variance parameter, it seems natural to want a distribution with nonnegative support and with decreasing density as you move away from 0 (e.g., exponential distribution). On the other hand, smaller values of the residual variance correspond to larger values of R^2 for the regression, so a prior on the residual variance concentrated around 0 seems to imply a prior on R^2 concentrated around 1, which doesn't seem like a very sensible default for most situations -- it seems like you'd probably want a prior on R^2 to have most density closer to 0, which would imply a prior on the residual variance with most density closer to var(Y), i.e., decreasing rather than increasing density as you move down toward 0. So I'm not really sure. Anyway, I see that you already changed this prior from uniform to half-t some time ago, which I think seems fine in practice and likely less surprising for users.
- Regardless of the above points on how well the current default priors work in theory and practice, there's the issue that they are unconventional and, for experienced users of Bayesian analysis, likely unexpected. I have wondered if this is a turn-off for some users that bambi handles these defaults basically differently from any other Bayesian regression package, and that the method it uses is only laid out in one non-peer reviewed paper on arxiv. Then again, maybe most users just plot the default priors, see that they look sensible enough, and don't think much more about it. I don't know.
- One of the primary appealing aspects of the approach we developed, in my mind, was that each default slope prior comes with an "informativeness" hyperparameter that has an intuitive interpretation in terms of its plausible partial correlations with the response, so it can be easily tuned by users. But in actual practice I think almost nobody actually tunes this parameter, they just leave it at the default value. In which case the intuitiveness of that parameter is sort of moot, and so the appeal is not as much as I'd hoped.

**Comment by aloctavodia** [comment] 2020-08-10 13:09
Thanks @jake-westfall  for your valuable feedback!

**Comment by canyon289** [comment] 2020-08-10 13:12
Likewise. It helps tremendously to have this historical context.

**Comment by tomicapretto** [comment] 2020-11-02 20:54
Hi @jake-westfall. I'm currently writing an example notebook on model comparison with Bambi + Arviz and I've been having some problems trying to fit some simple logistic regression models with default automatic priors and so I decided to look into the implementation of automatic priors. The error raised is this one 
```
ValueError: The first guess on the deviance function returned a nan.  This could be a boundary  problem and should be reported.
```
And it happens when you execute these lines
https://github.com/bambinos/bambi/blob/8786da98824cf8b4b942711810ffde04ae9ac3ba/bambi/priors.py#L247-L257.

As far as I understand, those lines are aimed to do what you explain here
![image](https://user-images.githubusercontent.com/25507629/97916740-2a4a1300-1d32-11eb-994a-1d7b863940e8.png)

After some trial and error, @aloctavodia and I figured out that passing `None` instead of `start_params=full_mod.params.values` to the `fit_constrained()` call this error disappeared (at least in the examples I ran). 

My intuition is that when you use the MLE of the unconstrained model as starting point to the IRLS algorithm when you constrain some \beta_j to be equal to some number between 0 and \hat{\beta_j} there is some kind of "incompatibility" that makes the algorithm to fail in terms of statsmodels implementation (but I'm not 100% sure).

So, my question is: Why do you use `start_params=full_mod.params.values` instead of `start_params=None`? I think that you did it thinking it would make the convergence faster, but I would like to know if there is another reason that I'm not understanding. 

Thank you!

**PS:** I can share an example notebook if you'd like to reproduce it on your side.

**Comment by jake-westfall** [comment] 2020-11-03 05:11
> So, my question is: Why do you use `start_params=full_mod.params.values` instead of `start_params=None`? I think that you did it thinking it would make the convergence faster

I believe that was my only reasoning, yes.

**Comment by aloctavodia** [comment] 2021-10-15 05:46
I am closing this issue, as we have effectively changed how we computed the automatic priors. Of course there is room for improvement, but at this point this seems more a matter of research than of implementation.

**Closed by aloctavodia** 2021-10-15 05:46 UTC
