### ISSUE TITLE
We need a level_map

### ISSUE THREAD

**Issue by jake-westfall** [bambinos/bambi#36] opened 2016-08-30 20:50 UTC

**Comment by tyarkoni** [comment] 2016-08-30 21:53
Yeah, definitely. It's a bit trickier now because we're using patsy to generate the design matrices in many places, but we should still be able to reach inside `.design_info.factor_infos` to get what we need. I think this might be a duplicate of #24 though, unless you're thinking of a different use case.

**Closed** 2016-09-12 22:27 UTC
Labels: enhancement
