### ISSUE TITLE
`predict` fails with Variational Inference

### ISSUE THREAD

**Issue by omrihar** [bambinos/bambi#572] opened 2022-10-10 10:15 UTC
I'm trying to use predict on out of sample data after sampling using variational inference. When I try to predict I get an "unexpected dimensions" error.

Minimal code to reproduce:
```python
import pandas as pd
import bambi as bmb

test_model = bmb.Model('y ~ x', pd.DataFrame({'x': [1,2,3], 'y': [2, 3, 4]}))
test_approx = test_model.fit(inference_method='vi')
test_tr = test_approx.sample(draws=1000)

test_model.predict(idata=test_tr, data=pd.DataFrame({'x': [4, 5], 'y': [1,1]}))
```

**Comment by tomicapretto** [comment] 2022-10-11 12:06
There's definitely something going on. The predictor `x` has a dimension when it shouldn't. 

![image](https://user-images.githubusercontent.com/25507629/195084325-bcf56162-d10b-4497-9ab9-ca1f661269a5.png)

I tried reproducing the issue with PyMC, and I couldn't. So I realized it is something about how Bambi builds the model.

Then I looked into the random variables in the underlying PyMC model and found the problem:

```python
test_model.backend.model.free_RVs
# [Intercept ~ N(3, 5.4), x ~ N(0, 2.5), y_sigma ~ HalfStudentT(4, 0.816)]
test_model.backend.model.free_RVs[1].shape
# TensorConstant{(1,) of 1}
```

which means that the distribution assigned for the slope is 1 dimensional when it should scalar. That's why it adds an extra dimension.

If we have a look at the PyMC model, this does not happen

```python
import pymc as pm

x = [1, 2, 3]
y = [2, 3, 4]

with pm.Model() as pm_model:
    a = pm.Normal("a")
    b = pm.Normal("b")
    pm.Normal("y", mu=a + b * x, sigma=pm.HalfNormal("sigma"), observed=y)
```

```python
pm_model.free_RVs
# [a ~ N(0, 1), b ~ N(0, 1), sigma ~ N**+(0, 1)]
pm_model.free_RVs[1].shape
# TensorConstant{[]}
```

**Comment by omrihar** [comment] 2022-10-19 11:53
Is there a way to circumvent this until the PR gets merged? For example, changing the dimensionality of the scalars after fitting, so that the predict method would work?

**Comment by tomicapretto** [comment] 2022-10-19 13:25
I don't know. But if you don't want to wait until the PR is merged, you can monkey-patch Bambi locally changing only these lines

```python
shape = None if data.shape[1] == 1 else data.shape
coef = distribution(label, shape=shape, **args)
coef = at.atleast_1d(coef)
```

in line 51 of `bambi/backend/terms.py`. 

See the screenshot 

![image](https://user-images.githubusercontent.com/25507629/196703945-30a7f4ce-9fec-43da-837f-1d0dbb5cacc1.png)

All the other changes are related to predictions

**Comment by tomicapretto** [comment] 2022-10-22 01:26
Since #575 is merged, we can close this one. Thanks for reporting the issue @omrihar!

**Closed by tomicapretto** 2022-10-22 01:26 UTC
Labels: bug
