### ISSUE TITLE
Allow to make predictions without considering group-specific effects.

### ISSUE THREAD

**Issue by alexjonesphd** [bambinos/bambi#469] opened 2022-03-13 21:15 UTC
Hello all,

First off I just want to say thank you for all the hard work on this amazing package! I love it and it gets better all the time. 

I have a question about predicting new data with a hierarchical model, specifically around how to handle the random/group effects. In my particular use case I have a model with two random intercept terms and fixed effects that include the interaction between three variables; two of which are continuous and the other categorical. My approach to exploring the interaction is to build a small 'test' dataset that fixes the continuous variables to a given value (e.g. ±2 SD) along with the categorical variable, and then pass them to the `.predict` method of a fitted model to recover the posterior predictive distribution. 

When doing this I notice errors if I omit either random effect term, and specifically that test values of the random effects **must** have a value in the actual dataset. My understanding is this allows me to predict the distribution of new observed data for my fixed effects set at my test levels for whatever combination of random effect A and B I choose (for example pupil A in school 1).

Previously I've done most of my hierarchical models from a frequentist perspective using `R`'s `lmer` package; and making predictions there is typically (and perhaps seemingly) random effect free - I guess from some kind of `newX @ fixed_beta` calculation. My question is whether a) this is a valid way to think about predictions from mixed models in a Bayesian context, and b) if so would this be possible in `bambi`? 

My approach at the moment has been to make a 'test' version of each combination of random effects - say for pupil A in school 1 predict the values for the varying combinations of fixed effects; have the model predict each one of these, and subsequently average over the fixed effects and chains/draws to arrive at a final distribution of each of the combinations of the fixed effects. This seems intuitive ('integrate over nuisance parameters') but I'm not confident this is correct, so any guidance is appreciated. 

Thanks for reading and the awesome package, and happy to share code/data if this is too vague!

**Comment by tomicapretto** [comment] 2022-03-13 22:15
Hi @alexjonesphd,

Thanks for the kind words about the package and for sharing your experience with it here.

For the sake of reproducibility, it would be better if you included a chunk of code together with a toy dataset so the problem is clear to everyone reading this. On the other hand, I think I understand what you mean. In short, you want to obtain predictions with the group-specific effects set to 0.

This feature is not available in Bambi right now, but it shouldn't be too much work to implement either. All we need to do is adding a parameter to `Model.predict()` that indicates we don't want to use group-specific effects in the prediction. That flag could be added in the following line

https://github.com/bambinos/bambi/blob/0febf5da08a9caf9fd140d9df0164f25c556b466/bambi/models.py#L864

This feature, and other more advanced variants such as marginalization over certain varying effects, is available in `brms`, a package where we take a lot of inspiration from.

Do you think you could open a PR? I could review it and help if needed.

**Comment by alexjonesphd** [comment] 2022-03-13 23:45
Hey @tomicapretto,

Yes, that's _exactly_ what I was looking for - setting the group-specific effects to 0! I've never actually opened a PR in my life so I might be making more work for you but I am happy to try. Looking through the code it seems straightforward to at least set the group-specific effects to zero by including a boolean argument as you suggest above; would it really be that easy?

Looking at `brms` I can see that the `predict` function there offers the option to marginalise over various group-specific effects with a `re_formula` flag. I guess if we wanted to implement this functionality we'd need to do something more complex, filtering out the group-specific terms from the formula object around line 866. `keep_group_specific` or its eventual kwarg could be made to control that too, if there's interest! 

Thanks again!

**Comment by tomicapretto** [comment] 2022-03-14 00:37
> Looking through the code it seems straightforward to at least set the group-specific effects to zero by including a boolean argument as you suggest above; would it really be that easy?

Yes, I think so. At least you can try on your side and test with your example.

> Looking at brms I can see that the predict function there offers the option to marginalise over various group-specific effects with a re_formula flag

I think this marginalization is not that trivial to implement. I need to double-check how it works. I'm not sure if it is as simple as filtering out group-specific terms (maybe it's the case, but I would like to check).

---

For the contribution, you can have a look at our [contributing guide](https://github.com/bambinos/bambi/blob/main/CONTRIBUTING.md).

**Comment by alexjonesphd** [comment] 2022-03-14 10:52
I tried a local change and it worked with no problems, it really was that simple. 

I will try a PR for this. I don't know how common marginalization is over certain group-specific effects, but my guess is setting them to zero is more popular and useful functionality to have right now. Thanks so much @tomicapretto!

**Comment by tomicapretto** [comment] 2022-04-10 00:19
Closing since #470 has been merged

**Closed by tomicapretto** 2022-04-10 00:19 UTC
Labels: enhancement
