### ISSUE TITLE
Missing priors for `family='negativebinomial'`?

### ISSUE THREAD

**Issue by No-Stream** [bambinos/bambi#323] opened 2021-03-31 04:24 UTC
Hi, I'm attempting to fit with the `negativebinomial` family and running into an error, despite it being listed as a valid family in the docs. I browsed around the codebase and looks like this config file might be lacking prior specs for negative binomial? 
https://github.com/bambinos/bambi/blob/master/bambi/config/priors.json

```/opt/anaconda3/envs/jan/lib/python3.7/site-packages/bambi/models.py in fit(self, formula, priors, family, link, run, categorical, omit_offsets, backend, **kwargs)
    283         if self._design.response is not None:
    284             _family = family.name if isinstance(family, Family) else family
--> 285             self._add_response(self._design.response, family=_family, link=link)
    286 
    287         if self._design.common:

/opt/anaconda3/envs/jan/lib/python3.7/site-packages/bambi/models.py in _add_response(self, response, prior, family, link)
    329         """
    330         if isinstance(family, str):
--> 331             family = self.default_priors.get(family=family)
    332         self.family = family
    333 

/opt/anaconda3/envs/jan/lib/python3.7/site-packages/bambi/priors.py in get(self, dist, term, family)
    189         elif family is not None:
    190             if family not in self.families:
--> 191                 raise ValueError(f"{family} is not a valid family name.")
    192             _f = self.families[family]
    193             prior = self._get_prior(_f["dist"])

ValueError: negativebinomial is not a valid family name.
```

**Comment by canyon289** [comment] 2021-03-31 05:30
Unfortunately you're right. It looks like that docstring for families is much out of date. Although not the ideal response I wont be able to add Negative Binomial anytime soon. So I have a couple proposals.

For you Jan, perhaps use PyMC3 directly. Itll be more lines of code but it'll get the job done
https://docs.pymc.io/notebooks/GLM-negative-binomial-regression.html.

For the other maintainers can we remove `negativebinomial`, `gama` (per spelling in docs) and `wald`. We also can add `t` distribution since that is specified. In addition to this also just add tests to see if the model compiles? 
https://github.com/bambinos/bambi/blob/master/bambi/priors.py#L177-L178

**Comment by canyon289** [comment] 2021-03-31 05:32
For the maintainers it seems like this discussion is related https://github.com/bambinos/bambi/issues/310#issuecomment-792245946

**Comment by aloctavodia** [comment] 2021-03-31 05:42
Thanks @No-Stream for taking the time to report this issue. @canyon289 not clear to me why you propose to remove families instead of fixing the config file so they actually work.

**Comment by No-Stream** [comment] 2021-03-31 05:45
@canyon289 I actually have some code fitting this directly in PyMC3, so it's not an issue to just use pymc3. (Said PyMC3 model is a little more complex, so wanted to quickly fit a linear model for model comparison purposes.) 

My hope was it was a simple matter of adding a few lines to the config.

**Comment by aloctavodia** [comment] 2021-03-31 05:47
You are right @No-Stream, in principle this can be fixed by updating the config file.

**Comment by canyon289** [comment] 2021-04-02 00:43
@No-Stream, @tomicapretto was kind enough to fix this in the PR above. Hopefully things work now if you install from master. I'll follow up with a test and if you're able to confirm its working for you I'll close this.

Also, I forgot my manners earlier. Thank you for opening this issue and making it so detailed!

**Comment by tomicapretto** [comment] 2021-04-06 13:38
Happy to re-open this issue if you still encounter problems with negative binomial family. Again, thanks for reporting the problem :)

**Closed by tomicapretto** 2021-04-06 13:38 UTC
